CREATE TABLE SALESPERSONS(
	SP_ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(2),
	ZIP VARCHAR(5),
	EMAIL VARCHAR(255),
	JOB_TITLE VARCHAR(255),
	PRIMARY KEY(SP_ID)
);

CREATE TABLE CUSTOMERS(
	CUST_ID INT GENERATED ALWAYS AS IDENTITY,
	SP_ID INT,
	NAME VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(2),
	ZIP VARCHAR(5),
	COMPANY VARCHAR(50),
	COMPANY_GROSS_INCOME_DOLLARS FLOAT(25),
	PRIMARY KEY(CUST_ID),
	FOREIGN KEY (SP_ID) REFERENCES SALESPERSONS(SP_ID),
	UNIQUE (CUST_ID, SP_ID)
);

CREATE TABLE PRODUCTS(
	P_ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	PRIMARY KEY(P_ID),
	UNIQUE (NAME)
);

CREATE TABLE OWN(
	O_ID SERIAL,
	CUST_ID INT NOT NULL,
	P_ID INT NOT NULL,
 	PRIMARY KEY (O_ID),
	FOREIGN KEY (P_ID) REFERENCES PRODUCTS(P_ID),
	FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
	CONSTRAINT OWNER UNIQUE (O_ID, CUST_ID)
);

CREATE TABLE EMPLOYEES(
	EMP_ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(2),
	ZIP VARCHAR(5),
	PHONE VARCHAR(25),
	EMAIL VARCHAR(255),
	PRIMARY KEY(EMP_ID)
);

CREATE TABLE CASES(
	CASE_ID INT GENERATED ALWAYS AS IDENTITY,
	SUMMARY VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255),
	STATUS BOOLEAN NOT NULL,
	EMP_ID INT NOT NULL,
	O_ID INT NOT NULL,
	TIMEOPENED DATE NOT NULL,
	TIMECLOSED DATE,
	PRIMARY KEY(CASE_ID),
	FOREIGN KEY (O_ID) REFERENCES OWN(O_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

CREATE TABLE CASE_COMMENTS(
	COM_ID INT GENERATED ALWAYS AS IDENTITY,
	CASE_ID INT NOT NULL,
	COMMENT_TIME TIME NOT NULL,
	COMMENT_DATE DATE NOT NULL,
	CASE_COMMENT VARCHAR(255) NOT NULL,
	PRIMARY KEY(COM_ID),
	FOREIGN KEY (CASE_ID) REFERENCES CASES(CASE_ID),
	UNIQUE (CASE_ID, COM_ID)
);

CREATE TABLE RESOLUTIONS(
	RES_ID INT GENERATED ALWAYS AS IDENTITY,
	RES_NAME VARCHAR(255) NOT NULL,
	STEPS VARCHAR(255) NOT NULL,
	CASE_ID INT NOT NULL,
	PRIMARY KEY(RES_ID),
	FOREIGN KEY (CASE_ID) REFERENCES CASES(CASE_ID),
	UNIQUE(CASE_ID)
);

/* Do we actually need this table? */
CREATE TABLE SELL(
	SELL_ID SERIAL,
	SP_ID INT NOT NULL,
	P_ID INT NOT NULL,
 	PRIMARY KEY (SELL_ID),
	FOREIGN KEY (SP_ID) REFERENCES SALESPERSONS(SP_ID),
	FOREIGN KEY (P_ID) REFERENCES PRODUCTS(P_ID)
);

/* Creating Indexes */
CREATE INDEX IX_CUSTOMERS1 on CUSTOMERS(CUST_ID, NAME);

CREATE INDEX IX_PRODUCTS1 on PRODUCTS(P_ID, NAME);

CREATE INDEX IX_EMPLOYEES1 on EMPLOYEES(EMP_ID, NAME);

CREATE INDEX IX_CASES1 on CASES(CASE_ID, P_ID, CUST_ID, STATUS, TIMEOPENED, TIMECLOSED);

CREATE INDEX IX_RESOLUTIONS1 on RESOLUTIONS(RES_ID, PRODUCT);



/* LIST OF QUERIES AND DESCRIPTION OF THEIR FUNCTIONALITY */

/* Search for a list of all available products */
SELECT *
FROM PRODUCTS

/* Search for products owned by a specific customer */
SELECT C.NAME, P.NAME AS PRODUCT, COUNT(P.NAME)
FROM PRODUCTS P, CUSTOMERS C, OWN O
WHERE O.P_ID = P.P_ID AND O.CUST_ID = C.CUST_ID
AND C.NAME LIKE '%Bart Simpson%'
GROUP BY P.NAME, C.NAME 
ORDER BY C.NAME

/* Search for personal and contact information about a customer */
SELECT NAME, STREET, CITY, STATE, ZIP, COMPANY, COMPANY_GROSS_INCOME_DOLLARS
FROM CUSTOMERS
WHERE NAME LIKE '%Bart%'

/* See general information for a specific case given the case number (status, customer name, product, case summary, case description, case comments)
SELECT DISTINCT CA.CASE_ID, CA.STATUS, CU.NAME, P.NAME, CA.SUMMARY, CA.DESCRIPTION, CA.TIMEOPENED, CA.TIMECLOSED, CC.CASE_COMMENT 
FROM CASES CA, CUSTOMERS CU, RESOLUTIONS R, CASE_COMMENTS CC, OWN O, PRODUCTS P
WHERE CA.CASE_ID = 1
AND CA.O_ID = O.O_ID AND O.CUST_ID = CU.CUST_ID AND O.P_ID = P.P_ID AND CC.CASE_ID = CA.CASE_ID

/* Search for cases by status and timeframe */
SELECT *
FROM CASES
WHERE STATUS = TRUE 
AND TIMEOPENED >= '20210303' AND TIMECLOSED <= '20210508'

/* Search for common resolutions by product */
SELECT P.NAME, R.RES_NAME, R.STEPS
FROM RESOLUTIONS R, CASES C, OWN O, PRODUCTS P
WHERE R.CASE_ID = C.CASE_ID AND C.O_ID = O.O_ID AND O.P_ID = P.P_ID
AND P.NAME = 'Alphalax'

/* Search for cases by product */
SELECT *
FROM CASES C, PRODUCTS P, OWN O
WHERE O.O_ID = C.O_ID AND O.P_ID = P.P_ID
AND P.NAME = 'Alphalax'

/* Search for cases by customer */
SELECT CU.NAME, CA.CASE_ID, CA.STATUS, CA.EMP_ID, CA.SUMMARY, CA.DESCRIPTION, CA.TIMEOPENED, CA.TIMECLOSED 
FROM CASES CA, CUSTOMERS CU, OWN O
WHERE CA.O_ID = O.O_ID AND O.CUST_ID = CU.CUST_ID 
AND CU.NAME LIKE '%Bart Simpson%'

/* Number of Support Cases by Product (ordered by largest) */
SELECT P.NAME as PRODUCT, COUNT(CASE_ID) as CASE_COUNT
FROM CASES C, PRODUCTS P, OWN O
WHERE C.O_ID = O.O_ID AND O.P_ID = P.P_ID
GROUP BY P.NAME
ORDER BY COUNT(CASE_ID) DESC

/* Number of Support Cases Closed by Employee (ordered by largest) */
SELECT E.NAME, COUNT(CASE_ID) as CASE_COUNT
FROM CASES C, EMPLOYEES E
WHERE C.EMP_ID = E.EMP_ID AND C.STATUS = FALSE
GROUP BY E.NAME
ORDER BY COUNT(CASE_ID) DESC

/* Number of Support Cases by Customer (ordered by largest) */
SELECT CU.NAME, COUNT(CASE_ID) as CASE_COUNT
FROM CASES CA, CUSTOMERS CU, OWN O
WHERE CA.O_ID = O.O_ID AND O.CUST_ID = CU.CUST_ID
GROUP BY CU.NAME
ORDER BY COUNT(CASE_ID) DESC

/* Number of Support cases by customer’s company(ordered by largest) */
SELECT CU.COMPANY, COUNT(CASE_ID) as CASE_COUNT
FROM CASES CA, CUSTOMERS CU, OWN O
WHERE CA.O_ID = O.O_ID AND O.CUST_ID = CU.CUST_ID
GROUP BY CU.COMPANY
ORDER BY COUNT(CASE_ID) DESC

/* Total number of products sold, grouped by product */
SELECT P.NAME, COUNT(O.P_ID) as NUMBER_SOLD
FROM OWN O, PRODUCTS P
WHERE O.P_ID = P.P_ID
GROUP BY P.NAME
ORDER BY NUMBER_SOLD DESC

/* The total number of products that have been sold by individual salespeople, grouped by product */
SELECT S.NAME, P.NAME, COUNT(O.O_ID) AS Total_Products_Sold
FROM SALESPERSONS S, PRODUCTS P, OWN O, CUSTOMERS C
WHERE S.SP_ID = C.SP_ID AND C.CUST_ID = O.CUST_ID AND O.P_ID = P.P_ID
GROUP BY S.NAME, P.NAME
ORDER BY S.NAME, Total_Products_Sold DESC

/* The total amount of money a specific company has spent on products. */ 
SELECT distinct COMPANY, SUM(COMPANY_GROSS_INCOME_DOLLARS)
FROM CUSTOMERS
GROUP BY COMPANY

/* The number of cases a specific employee currently has opened and the number that employee has closed */
SELECT C.STATUS, COUNT(CASE_ID) as CASE_COUNT
FROM CASES C
WHERE C.EMP_ID = 1
GROUP BY C.STATUS
ORDER BY CASE_COUNT

