CREATE TABLE SALESPERSONS(
	SP_ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(2),
	ZIP VARCHAR(5),
	EMAIL VARCHAR(255),
	JOB_TITLE VARCHAR(255),
	PRIMARY KEY(SP_ID)
);

CREATE TABLE CUSTOMERS(
	CUST_ID INT GENERATED ALWAYS AS IDENTITY,
	SP_ID INT,
	NAME VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(2),
	ZIP VARCHAR(5),
	COMPANY VARCHAR(50),
	COMPANY_GROSS_INCOME_DOLLARS FLOAT(25),
	PRIMARY KEY(CUST_ID),
	FOREIGN KEY (SP_ID) REFERENCES SALESPERSONS(SP_ID),
	UNIQUE (CUST_ID, SP_ID)
);

CREATE TABLE PRODUCTS(
	P_ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	PRIMARY KEY(P_ID),
	UNIQUE (NAME)
);

CREATE TABLE OWN(
	O_ID SERIAL,
	CUST_ID INT NOT NULL,
	P_ID INT NOT NULL,
 	PRIMARY KEY (O_ID),
	FOREIGN KEY (P_ID) REFERENCES PRODUCTS(P_ID),
	FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
	CONSTRAINT OWNER UNIQUE (O_ID, CUST_ID)
);

CREATE TABLE EMPLOYEES(
	EMP_ID INT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(255) NOT NULL,
	STREET VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(2),
	ZIP VARCHAR(5),
	PHONE VARCHAR(25),
	EMAIL VARCHAR(255),
	PRIMARY KEY(EMP_ID)
);

CREATE TABLE CASES(
	CASE_ID INT GENERATED ALWAYS AS IDENTITY,
	SUMMARY VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255),
	STATUS BOOLEAN NOT NULL,
	EMP_ID INT NOT NULL,
	O_ID INT NOT NULL,
	TIMEOPENED DATE NOT NULL,
	TIMECLOSED DATE,
	PRIMARY KEY(CASE_ID),
	FOREIGN KEY (O_ID) REFERENCES OWN(O_ID),
	FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

CREATE TABLE CASE_COMMENTS(
	COM_ID INT GENERATED ALWAYS AS IDENTITY,
	CASE_ID INT NOT NULL,
	COMMENT_TIME TIME NOT NULL,
	COMMENT_DATE DATE NOT NULL,
	CASE_COMMENT VARCHAR(255) NOT NULL,
	PRIMARY KEY(COM_ID),
	FOREIGN KEY (CASE_ID) REFERENCES CASES(CASE_ID),
	UNIQUE (CASE_ID, COM_ID)
);

CREATE TABLE RESOLUTIONS(
	RES_ID INT GENERATED ALWAYS AS IDENTITY,
	RES_NAME VARCHAR(255) NOT NULL,
	STEPS VARCHAR(255) NOT NULL,
	CASE_ID INT NOT NULL,
	PRIMARY KEY(RES_ID),
	FOREIGN KEY (CASE_ID) REFERENCES CASES(CASE_ID),
	UNIQUE(CASE_ID)
);

/* Do we actually need this table? */
CREATE TABLE SELL(
	SELL_ID SERIAL,
	SP_ID INT NOT NULL,
	P_ID INT NOT NULL,
 	PRIMARY KEY (SELL_ID),
	FOREIGN KEY (SP_ID) REFERENCES SALESPERSONS(SP_ID),
	FOREIGN KEY (P_ID) REFERENCES PRODUCTS(P_ID)
);

/* Creating Indexes */
CREATE INDEX IX_CUSTOMERS1 on CUSTOMERS(CUST_ID, NAME);

CREATE INDEX IX_PRODUCTS1 on PRODUCTS(P_ID, NAME);

CREATE INDEX IX_EMPLOYEES1 on EMPLOYEES(EMP_ID, NAME);

CREATE INDEX IX_CASES1 on CASES(CASE_ID, P_ID, CUST_ID, STATUS, TIMEOPENED, TIMECLOSED);

CREATE INDEX IX_RESOLUTIONS1 on RESOLUTIONS(RES_ID, PRODUCT);

